// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCklnrWyjt8Sb3dO6Ec-7Oe1WTHT-KHr8Q',
    appId: '1:529874641897:web:df6c266c95a72191c5e178',
    messagingSenderId: '529874641897',
    projectId: 'police-election',
    authDomain: 'police-election.firebaseapp.com',
    storageBucket: 'police-election.appspot.com',
    measurementId: 'G-0NSBBW9CN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARLY_wAdgyhfIgMwHRXPoj14tx8bQwLFI',
    appId: '1:529874641897:android:631babebbcb8b646c5e178',
    messagingSenderId: '529874641897',
    projectId: 'police-election',
    storageBucket: 'police-election.appspot.com',
  );
}
