List<List<Map<String, dynamic>>> detail = [
  [
    //P1
    {
      'CenterName': 'प्राथमिक विद्यालय औडौली',
      'PSName': 'राबर्ट्सगंज',
      'PSLNumber': '294',
      'SectorNumber': '35',
      'SMName': 'श्री शिवेन्द्र प्रताप सिंह श्रम प्रवर्तन अधिकारी रावर्टसगंज',
      'SMContact': '9670759115',
      'ZoneNumber': '8',
      'ZMName':
          'श्री गौरी शंकर गुप्ता, अधिशासी अभियन्ता, लघु सिचाई खण्ड, सोनभद्र।',
      'ZMContact': '9918758777',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'कम्‍पोजिट विद्यालय सुकृत क0 नं0 १ . 2 .3',
      'PSName': 'राबर्ट्सगंज',
      'PSLNumber': '302 से 304',
      'SectorNumber': '25',
      'SMName':
          'श्री अविनाश कौशल, अवर अभियन्ता पी०एम०जी०एस०वाई० लो०नि०वि०. सोनभद्र।',
      'SMContact': '8005173500',
      'ZoneNumber': '7',
      'ZMName':
          'श्री महेन्द्र सिंह, अधिशासी अभियन्ता, जल निगम (ग्रामीण), सोनभद्र।',
      'ZMContact': '8317075308',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'कम्‍पोजिट विद्यालय तकिया क0 नं0 १ से 2',
      'PSName': 'राबर्ट्सगंज',
      'PSLNumber': '307 से 308',
      'SectorNumber': '25',
      'SMName':
          'श्री अविनाश कौशल, अवर अभियन्ता पी०एम०जी०एस०वाई० लो०नि०वि०. सोनभद्र।',
      'SMContact': '8005173500',
      'ZoneNumber': '7',
      'ZMName':
          'श्री महेन्द्र सिंह, अधिशासी अभियन्ता, जल निगम (ग्रामीण), सोनभद्र।',
      'ZMContact': '8317075308',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'कम्‍पोजिट विद्यालय लोहरा क0 नं0 १ से 2',
      'PSName': 'राबर्ट्सगंज',
      'PSLNumber': '309 से 310',
      'SectorNumber': '25',
      'SMName':
          'श्री अविनाश कौशल, अवर अभियन्ता पी०एम०जी०एस०वाई० लो०नि०वि०. सोनभद्र।',
      'SMContact': '8005173500',
      'ZoneNumber': '7',
      'ZMName':
          'श्री महेन्द्र सिंह, अधिशासी अभियन्ता, जल निगम (ग्रामीण), सोनभद्र।',
      'ZMContact': '8317075308',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्राथमिक विद्यालय गौरही कमरा नं0 १ से 2',
      'PSName': 'राबर्ट्सगंज',
      'PSLNumber': '318 से 319',
      'SectorNumber': '25',
      'SMName':
          'श्री अविनाश कौशल, अवर अभियन्ता पी०एम०जी०एस०वाई० लो०नि०वि०. सोनभद्र।',
      'SMContact': '8005173500',
      'ZoneNumber': '7',
      'ZMName':
          'श्री महेन्द्र सिंह, अधिशासी अभियन्ता, जल निगम (ग्रामीण), सोनभद्र।',
      'ZMContact': '8317075308',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्राथमिक विद्यालय नागनार हरैया कक्ष सं0 १ .2 .3',
      'PSName': 'राबर्ट्सगंज',
      'PSLNumber': '338 से 340',
      'SectorNumber': '26',
      'SMName':
          'श्री रामनिवास पाण्डेय अवर अभियन्ता ग्रामीण अभियंत्रण विभाग सोनभद्र',
      'SMContact': '9415874515',
      'ZoneNumber': '7',
      'ZMName':
          'श्री महेन्द्र सिंह, अधिशासी अभियन्ता, जल निगम (ग्रामीण), सोनभद्र।',
      'ZMContact': '8317075308',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'क0वि0 रघुनाथपुर कक्ष सं0 १ से 2',
      'PSName': 'राबर्ट्सगंज',
      'PSLNumber': '365 से 366',
      'SectorNumber': '39',
      'SMName':
          'श्री रामप्यारे दूबे सहायक अभियन्ता निर्माण खण्ड -2 लो0नि0वि0 सोनभद्र',
      'SMContact': '9415264297',
      'ZoneNumber': '10',
      'ZMName': 'श्री जय प्रकाश, उप कृषि निदेशक, सोनभद्र।',
      'ZMContact': '9793737244',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्राथमिक विद्यालय गोरडीहां',
      'PSName': 'राबर्ट्सगंज',
      'PSLNumber': '376',
      'SectorNumber': '40',
      'SMName': 'डा0 अशोक कुमार अपर सांख्यिकीय अधिकारी सोनभद्र',
      'SMContact': '7007219012',
      'ZoneNumber': '10',
      'ZMName': 'श्री जय प्रकाश, उप कृषि निदेशक, सोनभद्र।',
      'ZMContact': '9793737244',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'नवीन अतिरिक्‍त कक्ष प्राथमिक विद्यालय पेटराही',
      'PSName': 'राबर्ट्सगंज',
      'PSLNumber': '420',
      'SectorNumber': '40',
      'SMName': 'डा0 अशोक कुमार अपर सांख्यिकीय अधिकारी सोनभद्र',
      'SMContact': '7007219012',
      'ZoneNumber': '10',
      'ZMName': 'श्री जय प्रकाश, उप कृषि निदेशक, सोनभद्र।',
      'ZMContact': '9793737244',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0कुसम्हा प्रथम',
      'PSName': 'राबर्ट्सगंज',
      'PSLNumber': '88',
      'SectorNumber': '50',
      'SMName': 'श्री शरद पाल खाद्य सुरक्षा अधिकारी सोनभद्र',
      'SMContact': '7275755757',
      'ZoneNumber': '12',
      'ZMName':
          'श्री रूपेश कुमार खरे, अधिशासी अभियन्ता, ओबरा बांध, प्रखण्ड, ओबरा, सोनभद्र।',
      'ZMContact': '9935705953',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0कुसम्हा द्वितीय',
      'PSName': 'राबर्ट्सगंज',
      'PSLNumber': '89',
      'SectorNumber': '50',
      'SMName': 'श्री शरद पाल खाद्य सुरक्षा अधिकारी सोनभद्र',
      'SMContact': '7275755757',
      'ZoneNumber': '12',
      'ZMName':
          'श्री रूपेश कुमार खरे, अधिशासी अभियन्ता, ओबरा बांध, प्रखण्ड, ओबरा, सोनभद्र।',
      'ZMContact': '9935705953',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'राबर्ट्सगंज PSQRT',
      'PSName': 'राबर्ट्सगंज',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'SST सुकृत चौकी के सामने',
      'PSName': 'राबर्ट्सगंज',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'एफएसटी तृतीय चौकी सुकृत',
      'PSName': 'राबर्ट्सगंज',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
  ],
  [
    //P2
    {
      'CenterName': 'पंचायत भवन बेलाटाड़',
      'PSName': 'शाहगंज',
      'PSLNumber': '173',
      'SectorNumber': '18',
      'SMName':
          'श्री नीरज शर्मा प्रवक्ता जिला शिक्षा एवं प्रशिक्षण संस्थान सोनभद्र ',
      'SMContact': '8707566651',
      'ZoneNumber': '4',
      'ZMName': 'डा0 सुरेश कुमार पाण्डेय, उप मुख्य पशु चिकित्साधिकारी, सोनभद्र',
      'ZMContact': '8840908114',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'जंगबहादुर इ0का0 ओडहथा',
      'PSName': 'शाहगंज',
      'PSLNumber': '177',
      'SectorNumber': '18',
      'SMName':
          'श्री नीरज शर्मा प्रवक्ता जिला शिक्षा एवं प्रशिक्षण संस्थान सोनभद्र',
      'SMContact': '8707566651',
      'ZoneNumber': '4',
      'ZMName': 'डा0 सुरेश कुमार पाण्डेय, उप मुख्य पशु चिकित्साधिकारी, सोनभद्र',
      'ZMContact': '8840908114',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
  ],
  [
    //P3
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
  ],
  [
    //P4
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
  ],
  [
    //P5
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
  ],
  [
    //P6
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
  ],
  [
    //P7
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
  ],
  [
    //P8
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
  ],
  [
    //P9
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
  ],
  [
    //P10
    {
      'CenterName': 'प्रा0वि0बसुहारी',
      'PSName': 'कोन',
      'PSLNumber': '274',
      'SectorNumber': '65',
      'SMName': 'श्री गोपाल शर्मा अवर अभियन्ता ग्रामीण अभियंत्रण विभाग सोनभद्र',
      'SMContact': '9450315449',
      'ZoneNumber': '15',
      'ZMName':
          'श्री अनिल कुमार राकेश, अधिशासी अभियन्ता, निर्माण खण्ड, लो0नि0वि0, सोनभद्र।',
      'ZMContact': '7906283546',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0चननी',
      'PSName': 'कोन',
      'PSLNumber': '275',
      'SectorNumber': '65',
      'SMName': 'श्री गोपाल शर्मा अवर अभियन्ता ग्रामीण अभियंत्रण विभाग सोनभद्र',
      'SMContact': '9450315449',
      'ZoneNumber': '15',
      'ZMName':
          'श्री अनिल कुमार राकेश, अधिशासी अभियन्ता, निर्माण खण्ड, लो0नि0वि0, सोनभद्र।',
      'ZMContact': '7906283546',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0रानीडीह',
      'PSName': 'कोन',
      'PSLNumber': '276',
      'SectorNumber': '65',
      'SMName': 'श्री गोपाल शर्मा अवर अभियन्ता ग्रामीण अभियंत्रण विभाग सोनभद्र',
      'SMContact': '9450315449',
      'ZoneNumber': '15',
      'ZMName':
          'श्री अनिल कुमार राकेश, अधिशासी अभियन्ता, निर्माण खण्ड, लो0नि0वि0, सोनभद्र।',
      'ZMContact': '7906283546',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0 पिण्डारी',
      'PSName': 'कोन',
      'PSLNumber': '277',
      'SectorNumber': '65',
      'SMName': 'श्री गोपाल शर्मा अवर अभियन्ता ग्रामीण अभियंत्रण विभाग सोनभद्र',
      'SMContact': '9450315449',
      'ZoneNumber': '15',
      'ZMName':
          'श्री अनिल कुमार राकेश, अधिशासी अभियन्ता, निर्माण खण्ड, लो0नि0वि0, सोनभद्र।',
      'ZMContact': '7906283546',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0 गड़ांव',
      'PSName': 'कोन',
      'PSLNumber': '278',
      'SectorNumber': '65',
      'SMName': 'श्री गोपाल शर्मा अवर अभियन्ता ग्रामीण अभियंत्रण विभाग सोनभद्र',
      'SMContact': '9450315449',
      'ZoneNumber': '15',
      'ZMName':
          'श्री अनिल कुमार राकेश, अधिशासी अभियन्ता, निर्माण खण्ड, लो0नि0वि0, सोनभद्र।',
      'ZMContact': '7906283546',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0चकरिया',
      'PSName': 'कोन',
      'PSLNumber': '280',
      'SectorNumber': '65',
      'SMName': 'श्री गोपाल शर्मा अवर अभियन्ता ग्रामीण अभियंत्रण विभाग सोनभद्र',
      'SMContact': '9450315449',
      'ZoneNumber': '15',
      'ZMName':
          'श्री अनिल कुमार राकेश, अधिशासी अभियन्ता, निर्माण खण्ड, लो0नि0वि0, सोनभद्र।',
      'ZMContact': '7906283546',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0बरहमोरी',
      'PSName': 'कोन',
      'PSLNumber': '281',
      'SectorNumber': '65',
      'SMName': 'श्री गोपाल शर्मा अवर अभियन्ता ग्रामीण अभियंत्रण विभाग सोनभद्र',
      'SMContact': '9450315449',
      'ZoneNumber': '15',
      'ZMName':
          'श्री अनिल कुमार राकेश, अधिशासी अभियन्ता, निर्माण खण्ड, लो0नि0वि0, सोनभद्र।',
      'ZMContact': '7906283546',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0ससनई',
      'PSName': 'कोन',
      'PSLNumber': '282',
      'SectorNumber': '73',
      'SMName':
          'श्री राममूर्ति पाल अवर अभियन्ता ग्रामीण अभियंत्रण विभाग सोनभद्र',
      'SMContact': '9450589789',
      'ZoneNumber': '17',
      'ZMName':
          'श्री शाहनवाज, अधिशासी अभियन्ता, खण्ड कार्यालय (वि0/यां0), उ0प्र0 जल निगम (ग्रामीण) सोनभद्र। ',
      'ZMContact': '9140851839',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0 पड़रछ (झिरंगादण्डी) प0पा0',
      'PSName': 'कोन',
      'PSLNumber': '283',
      'SectorNumber': '76',
      'SMName': 'श्री अनुज जायसवाल अवर अभियन्ता निर्माण खण्ड-2 रावर्टसगंज',
      'SMContact': '8081936208',
      'ZoneNumber': '18',
      'ZMName': 'श्री राजेन्द्र प्रसाद जिला विद्यालय निरीक्षक, सोनभद्र',
      'ZMContact': '9454457375',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0पड़रछ (भालूकूदर)',
      'PSName': 'कोन',
      'PSLNumber': '288',
      'SectorNumber': '77',
      'SMName':
          'श्री सुर्य लाल सिह अवर अभियंता प्राविधिक लो0नि0वि0 निर्माण खण्ड रावर्टसगंज',
      'SMContact': '8840816775',
      'ZoneNumber': '18',
      'ZMName': 'श्री राजेन्द्र प्रसाद जिला विद्यालय निरीक्षक, सोनभद्र',
      'ZMContact': '9454457375',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0पड़रछ सतद्वारी',
      'PSName': 'कोन',
      'PSLNumber': '289',
      'SectorNumber': '77',
      'SMName':
          'श्री सुर्य लाल सिह अवर अभियंता प्राविधिक लो0नि0वि0 निर्माण खण्ड रावर्टसगंज',
      'SMContact': '8840816775',
      'ZoneNumber': '18',
      'ZMName': 'श्री राजेन्द्र प्रसाद जिला विद्यालय निरीक्षक, सोनभद्र',
      'ZMContact': '9454457375',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0कुडवा (इस्लामिया नगर)',
      'PSName': 'कोन',
      'PSLNumber': '290',
      'SectorNumber': '76',
      'SMName': 'श्री अनुज जायसवाल अवर अभियन्ता निर्माण खण्ड-2 रावर्टसगंज',
      'SMContact': '8081936208',
      'ZoneNumber': '18',
      'ZMName': 'श्री राजेन्द्र प्रसाद जिला विद्यालय निरीक्षक, सोनभद्र',
      'ZMContact': '9454457375',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0हर्रा(पू0पा0) र्व  (प0पा0)',
      'PSName': 'कोन',
      'PSLNumber': '317 से 318',
      'SectorNumber': '76',
      'SMName': 'श्री अनुज जायसवाल अवर अभियन्ता निर्माण खण्ड-2 रावर्टसगंज',
      'SMContact': '8081936208',
      'ZoneNumber': '18',
      'ZMName': 'श्री राजेन्द्र प्रसाद जिला विद्यालय निरीक्षक, सोनभद्र',
      'ZMContact': '9454457375',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
    {
      'CenterName': 'प्रा0वि0नौडीहा (पू0पा0) व (प0पा0)',
      'PSName': 'कोन',
      'PSLNumber': '326 से 327',
      'SectorNumber': '76',
      'SMName': 'श्री अनुज जायसवाल अवर अभियन्ता निर्माण खण्ड-2 रावर्टसगंज',
      'SMContact': '8081936208',
      'ZoneNumber': '18',
      'ZMName': 'श्री राजेन्द्र प्रसाद जिला विद्यालय निरीक्षक, सोनभद्र',
      'ZMContact': '9454457375',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
  ],
  [
    //P11
    {
      'CenterName': '',
      'PSName': '',
      'PSLNumber': '',
      'SectorNumber': '',
      'SMName': '',
      'SMContact': '',
      'ZoneNumber': '',
      'ZMName': '',
      'ZMContact': '',
      'SHO/SO Name': '',
      'SHO/SO Contact': '',
    },
  ]
];
